name: Flutter CI/CD for Android and iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup Flutter Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'

  android:
    name: Build and Deploy Android App
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check Current Directory
        run: |
          pwd
          ls -l

      - name: Create Directory for Keystore
        run: |
          mkdir -p ../app

      - name: Set up Keystore
        run: |
          echo "${{ secrets.MY_RELEASE_KEY }}" | base64 --decode > ../app/my-release-key.jks

      - name: Debug Keystore Path
        run: |
          ls -l ../app/

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'

      - name: Increment Android Version
        run: |
          # Increment versionCode in app/build.gradle
          sed -i "s/versionCode [0-9]*/versionCode $(( $(grep versionCode android/app/build.gradle | awk '{print $2}') + 1 ))/" android/app/build.gradle
                
          # Increment versionName in app/build.gradle (add timestamp)
          sed -i "s/versionName \"[0-9\.]*\"/versionName \"9.$(date +%Y%m%d%H%M%S)\"/" android/app/build.gradle

      - name: Increment Flutter Version in pubspec.yaml
        run: |
          # Extract current version and increment build number
          current_version=$(grep '^version:' pubspec.yaml | awk '{print $2}')
          base_version=${current_version%%+*}
          build_number=${current_version##*+}
          new_build_number=$((build_number + 1))
          sed -i "s/^version: .*/version: 2.3.7+$(( $(grep '^version:' pubspec.yaml | awk -F+ '{print $2}') + 1 ))/" pubspec.yaml


      - name: Install Dependencies
        run: flutter pub get

     # - name: Run Flutter Tests
     #   run: flutter test

      - name: Build Android AppBundle (AAB)
        run: flutter build appbundle --release

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Deploy to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: com.johncolani.greate_note_app
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: production # Options: production, beta, alpha, internal

  ios:
    name: Build and Deploy iOS App
    needs: setup
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Increment iOS Version
        run: |
          # Increment build number in pubspec.yaml (handled in Android job above)
          # Update Info.plist version fields
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $(( $(/usr/libexec/PlistBuddy -c 'Print :CFBundleVersion' ios/Runner/Info.plist) + 1 ))" ios/Runner/Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString 2.3.$(date +%Y%m%d%H%M%S)" ios/Runner/Info.plist

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Flutter Tests
        run: flutter test

      - name: Build iOS IPA
        run: flutter build ipa --release

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-ipa
          path: build/ios/ipa

      - name: Deploy to App Store
        uses: appleboy/app-store-deploy-action@v1.0.0
        with:
          api_key_id: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          api_key_issuer_id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          api_key: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
          ipa: build/ios/ipa/app.ipa
